// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qznhxoejngpcaywcvvsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6bmh4b2VqbmdwY2F5d2N2dnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTY1ODAsImV4cCI6MjA2OTg5MjU4MH0.cxxSb7AcpYX1Wai7LVIrqEgvRUHyHG_xxO1Y2zb-RY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});